format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$gcloud\
$azure\
$docker_context\
$kubernetes\
$time\
$line_break\
$shell\
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false
[fill]
symbol = ' '

[line_break]
symbol = "\n"
disabled = false

# You can also replace your username with a neat symbol like  or disable this
# and use the os module below
[username]
show_always = true
style_user = "bold purple"
style_root = "bold red"
format = '[$user ]($style)'
disabled = false
aliases = {juliasilver = "⚝", root = "ROOT"}

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
disabled = false

[shell]
format = "[$indicator]($style) "
bash_indicator = "＄"
fish_indicator = "🐟"
zsh_indicator = "⚡"
powershell_indicator = ""
ion_indicator = "Ｉ"
elvish_indicator = "Ｅ"
tcsh_indicator = "Ｔ"
nu_indicator = "❖"
xonsh_indicator = "xsh"
cmd_indicator = "cmd"
unknown_indicator = ""
style = "white bold"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bold white"
disabled = false

[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = "💠 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
Artix = "🎗️ "
Bluefin = "🐟 "
CachyOS = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Macos = " "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
Nobara = "🎩 "
OpenBSD = "🐡 "
OpenCloudOS = " ☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "💠 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = "🎯 "
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = "  "
Windows = "🪟 "

[directory]
style = "bold white"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"git" = " "
"code" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = " "

[git_branch]
format = "[on $symbol$branch(:$remote_branch) ]($style)"
symbol = " "
style = "bold purple"
truncation_length = 20
truncation_symbol = "…"
only_attached = false
# always_show_remote = false
ignore_branches = []
disabled = false

[git_commit]
style = ""
commit_hash_length = 7
format = '[\($hash$tag\)]($style)'
# style = "green bold"
only_detached = true
disabled = false
tag_symbol = "🏷  "
tag_disabled = true
tag_max_candidates = 0

[git_metrics]
added_style = "bold green "
deleted_style = "bold red "
only_nonzero_diffs = true
format = "([+$added]($added_style))([-$deleted]($deleted_style))"
disabled = true
ignore_submodules = false

[git_state]
style = "bold yellow "
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
# style = "bold yellow"
format = '\([$state($progress_current/$progress_total)]($style)\)'
disabled = false

[git_status]
style = "red bold"
format = '[$all_status$ahead_behind]($style)'
# style = "red bold"
stashed = '\$'
ahead = "⇡"
behind = "⇣"
up_to_date = ""
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"
typechanged = ""
ignore_submodules = false
disabled = false
use_git_executable = false

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = ""
format = '[ ♥ $time ]($style)'

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = " ☁️ "
style = "bold yellow"
disabled = false
expiration_symbol = "X"
force_display = false

[aws.region_aliases]

[aws.profile_aliases]

[gcloud]
format = 'on [$symbol$account(@$domain)(\($region\))]($style) '
symbol = " ☁️ "
style = "bold blue"
disabled = false

[gcloud.region_aliases]

[gcloud.project_aliases]

[azure]
format = "on [$symbol($subscription)]($style) "
symbol = " ☁️ "
style = "bold blue"
disabled = true

[azure.subscription_aliases]

[kubernetes]
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "bold blue"
disabled = false

