
# install core gui tools
# vscode
  # recover backed up vscode settings from ~/.config/IDEs/vscode
# firefox
  # can firerfox configs be backed up and recovered?

# note differences for mac and linux